### ISSUE TITLE
Proposition

### ISSUE THREAD

**Issue by midnightchip** [blanxd/IPonCC#1]
Hey could I ask you a question, my email is midnightchips@gmail.com, I would like to ask permission to use your code, you will be credited in it.

**Comment by blanxd** [comment]
By all means.
/u/thecoderkiller was actually also asking the same, and I must be honest, some of my inspiration for making it as it is now (presentation wise) came from a question /u/simalary44 asked once on /r/jailbreakdevelopers, so you guys are absolutely welcome to use it :)
(I won't turn down on being credited of course :)
